# Generated by Django 4.1.6 on 2023-02-05 09:49

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tech_name1', models.CharField(max_length=50)),
                ('tech_name2', models.CharField(max_length=50)),
                ('tech_name3', models.CharField(max_length=50)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Note')),
            ],
        ),
    ]
