# Generated by Django 3.2.17 on 2023-02-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tech_name1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tech_name2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tech_name3',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
