# Generated by Django 3.2.17 on 2023-02-06 11:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_auto_20230206_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tech_name1', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_name2', models.CharField(blank=True, max_length=50, null=True)),
                ('tech_name3', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField()),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='Blog')),
            ],
        ),
    ]
