# Generated by Django 3.2 on 2023-02-10 10:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_dream_dreamcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('course_price', models.IntegerField()),
                ('course_discount_price', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='CourseImage')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('course_detail_link', models.URLField(blank=True, null=True, unique=True)),
                ('course_type', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Corporate', 'Corporate')], max_length=100)),
                ('total_class', models.CharField(blank=True, max_length=200, null=True)),
                ('duration', models.CharField(blank=True, max_length=200, null=True)),
                ('course_start_date', models.CharField(blank=True, max_length=200, null=True)),
                ('available_seat', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
