# Generated by Django 3.2 on 2023-02-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0008_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
    ]
