# Generated by Django 3.2 on 2023-02-10 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_remove_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='available_seat',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_discount_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_start_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
